### ISSUE TITLE
Make a plugin version

### ISSUE THREAD

**Issue by ThirteenAG** [praydog/alan-wake-2-cmdline-patcher#1]
Hey, can you add a dll project so it can be loaded by an asi loader?

Minimal example for [UAL](https://github.com/ThirteenAG/Ultimate-ASI-Loader):

```c
#include <windows.h>

#include <utility/Module.hpp>
#include <utility/Scan.hpp>
#include <utility/Patch.hpp>
#include <utility/Thread.hpp>
#include <utility/ScopeGuard.hpp>
#include <utility/RTTI.hpp>

bool ret1()
{
    return true;
}

void test()
{
    const auto vtable = utility::rtti::find_vtable(GetModuleHandle(NULL), "class std::_Func_impl_no_alloc<bool (__cdecl*)(void),bool>");

    if (!vtable)
        return;

    const auto rva = (uintptr_t*)*vtable;  
    auto vt_func_2 = &rva[2];
    Patch::protect((uintptr_t)vt_func_2, sizeof(uintptr_t), PAGE_EXECUTE_READWRITE);
    *vt_func_2 = (uintptr_t)ret1;
}

extern "C" __declspec(dllexport) void InitializeASI()
{
    __try
    {
        test();
    }
    __except ((GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ? EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
    {
    }
}
```

[aw2-cmdline-standalone.zip](https://github.com/praydog/alan-wake-2-cmdline-patcher/files/13327328/aw2-cmdline-standalone.zip)

**Comment by praydog** [comment]
Added in d229f0b072a65721b18d3c233197f835ae6642a4

`version.dll` doesn't seem to get in early enough, so not all command line args work correctly. Will keep the patcher around.

**Comment by ThirteenAG** [comment]
d3d12 works for me for skip intro related args, with the attached version, but not with the currently released. I'll check why.

**Comment by praydog** [comment]
542b0985f9b8fbc6b545a52b12631e514942b7a6

Should be fixed now. Was thinking that any of that code in there would indirectly try to load a DLL or something and deadlock DllMain. Guess not.

**Comment by ThirteenAG** [comment]
Yeah, was about to write that dllmain is the reason. I usually have a check for UAL for cases like this, but it requires [checking all modules](https://github.com/ThirteenAG/WidescreenFixesPack/blob/master/includes/ModuleList.hpp):

```c
bool IsModuleUAL(HMODULE mod)
{
    if (GetProcAddress(mod, "DirectInput8Create") != NULL && GetProcAddress(mod, "DirectSoundCreate8") != NULL && GetProcAddress(mod, "InternetOpenA") != NULL)
        return true;
    return false;
}

bool IsUALPresent()
{
    ModuleList dlls;
    dlls.Enumerate(ModuleList::SearchLocation::LocalOnly);
    for (auto& e : dlls.m_moduleList)
    {
        if (IsModuleUAL(std::get<HMODULE>(e)))
            return true;
    }
    return false;
}
```

Alternatively, for latest versions:

```c
    ModuleList dlls;
    dlls.Enumerate(ModuleList::SearchLocation::LocalOnly);
    for (auto& e : dlls.m_moduleList)
    {
        auto m = std::get<HMODULE>(e);
        if (GetProcAddress(m, "IsUltimateASILoader") != NULL)
            return;
    }
```


```c
BOOL APIENTRY DllMain(HMODULE hModule, DWORD reason, LPVOID lpReserved)
{
    if (reason == DLL_PROCESS_ATTACH)
    {
        if (!IsUALPresent()) { InitializeASI(); }
    }
    return TRUE;
}
```

Anyway, thanks, tested with UAL named d3d12.dll, bink2w64.dll, winmm.dll, works early enough with these. Indeed not early enough with version.dll.
